language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm install node-sass fur -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "OUX1E49kG3fVx4Q2b4QO9nJ0o3uRo4k2wYHFgw+BFzBXaS+lP1KkDoKrLZleVStoGxVWevB9TB8m1V3CIxmcEsOod5shimzQkfqCtFB1x2sUBSkN4tDJxvctTfhNB9hYAmUm5hvuJXGPFS6jecsx+SVC4lkH3Lq8qB328rGnNPboG/W5tEDPUVkACNre05cTbDgpqYoT7zmsK6rbluDPgVDlF4Z/RPM6RaNV2kV5mjUlBxUqF706WdIe2DucIZmDzqMCSuRJciKcjdRfjWsWpDWn7hT60//Jda5XH+kom/p2xX08ko9FMF8yDXH/VEuidBvxF/m5s/xNNKJpMPGlMVzHbV1xScEX7QX2iOkOdemMWt3ixU3JtsbJA1zl6/aQdKiofJvNa1ykI/DQwVCtdGLtGv1Vua/4f897FB57H06uBxkRRQnCtMxbwH8me62cUtP5on4O4FT157v+sXoa9YKf9NpnWq+/4UJWOCjtiYdGkAh2p8AdNTCEAcyodceiiWrOabOe0NrQ8ax0A8f6Ry+6uj0r6ReGF+RsfmE0tNudI3O3EhJPFLk3eKGW2HHdboXyVSt+zBSsJVSm5UYD4UN4mJszadmilfKya3NX/jjW0uvHdPSHSLMU8RtI+FT7lwOdZkisiuICDxVYENjaOlX9EOmcT5sisOcQ6JorvaY="
